In this notebook to cover:

*   Introduction to tensors
*   Getting information from tensor
*   Manipulating tensors
*   Tensors & NumPy
*   Using @tf.function (a way to boost up speed to a regular python function)
*   Using GPUs with Tensorflow
*   Exercises to try for yourself!





# Introduction to Tensors

In [1]:
# Import Tensroflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# tf.constent tensor
t_scale = tf.constant(7)
t_scale

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimension of a tensor (ndim)
t_scale.ndim

0

In [ ]:
# create a vector
vector_t = tf.constant([8,64])
vector_t

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 8, 64], dtype=int32)>

In [ ]:
#check the dimension of vector
vector_t.ndim

1

In [ ]:
# creating a matrix (1D)
matrix = tf.constant([[10,7],
                      [7,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 11]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
a_matrix = tf.constant([[11.5,9.3],
                        [13.8,5.2],
                         [9.3,6.5]])
a_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11.5,  9.3],
       [13.8,  5.2],
       [ 9.3,  6.5]], dtype=float32)>

In [ ]:
# lets check the dimensions of a_matrix
a_matrix.ndim

2

In [ ]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3


What created so far:

*   Scalar: a single number
*   Vector: a number with direction (e.g. wind speed and direction)
*   Matrix: a 2-dimensional array of numbers
*   Tensor: an n-dimensional array of numbers (when n can be any number, a *  
*   0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

# Creating tensors with tf.Variable


In [ ]:
# create the same tensor with tf.Variable()
changeable_tensor = tf.Variable([10,7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
changeable_tensor[0] = 70
changeable_tensor[1] = 100
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(70)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([70,  7], dtype=int32)>

In [ ]:
another_chnge_tensor = tf.Variable([[[10,5,6],[12,15,18,],[17,20,23]]])
another_chnge_tensor

<tf.Variable 'Variable:0' shape=(1, 3, 3) dtype=int32, numpy=
array([[[10,  5,  6],
        [12, 15, 18],
        [17, 20, 23]]], dtype=int32)>

In [ ]:
# prompt: another_chnge_tensor[1].assign([1,2,3])
# InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:CPU:0}} slice index 1 of dimension 0 out of bounds. [Op:StridedSlice] name: strided_slice/

another_chnge_tensor[0,0].assign([20,25,36])
another_chnge_tensor[0,1].assign([24,30,36])
another_chnge_tensor[0,2].assign([1,2,3])



<tf.Variable 'UnreadVariable' shape=(1, 3, 3) dtype=int32, numpy=
array([[[20, 25, 36],
        [24, 30, 36],
        [ 1,  2,  3]]], dtype=int32)>

In [ ]:
another_chnge_tensor

<tf.Variable 'Variable:0' shape=(1, 3, 3) dtype=int32, numpy=
array([[[20, 25, 36],
        [24, 30, 36],
        [ 1,  2,  3]]], dtype=int32)>

In [ ]:
# if i want to change it at a time . it can do this way
another_chnge_tensor[0].assign([[1,2,3],[4,5,6],[7,8,9]])
another_chnge_tensor

<tf.Variable 'Variable:0' shape=(1, 3, 3) dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [ ]:
# Let's try change our unchangable tensor
unchangeable_tensor = tf.constant([10, 7])
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

🔑 Note: Rarely in practice will you need to decide whether to use tf.constant or tf.Variable to create tensors, as TensorFlow does this for you. However, if in doubt, use tf.constant and change it later if needed.

# Creating random tensors
Random tensors are tensors of some arbitrary size which contain random numbers

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
g = tf.random.Generator.from_seed(1000)
g

In [ ]:
g.normal(shape=(1, 2, 3))

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[ 1.428492  , -0.11131959, -0.98949283],
        [-0.12332226, -1.9408084 ,  0.5852516 ]]], dtype=float32)>

In [ ]:
g.normal(shape=(2,5,5))

<tf.Tensor: shape=(2, 5, 5), dtype=float32, numpy=
array([[[ 0.18604636,  0.29385093,  0.5387022 , -0.3138002 ,
         -0.29538742],
        [-0.265005  ,  1.6288896 , -0.63644403, -0.4442133 ,
         -1.0491567 ],
        [ 0.2935164 ,  0.12024023,  0.6721148 , -0.48091418,
         -0.36095518],
        [-0.10644098,  0.5473122 ,  2.076657  ,  0.781174  ,
         -0.38105404],
        [-0.93199843,  0.5728476 , -0.7579853 , -0.10818893,
         -0.07310843]],

       [[ 0.40170723, -0.4118715 ,  1.0152366 , -0.37452048,
          0.7287674 ],
        [ 1.0916955 , -0.56821287,  0.05188959,  0.2997935 ,
         -0.47533965],
        [ 0.3137532 , -1.389889  ,  1.3457667 , -1.0083542 ,
         -2.1767304 ],
        [-1.1458926 , -1.2985514 ,  1.2916592 , -0.9279968 ,
         -0.56358933],
        [-1.1475383 , -2.3410347 ,  0.6897158 ,  0.63634926,
          0.707515  ]]], dtype=float32)>

On the above cover:

* tf.random.Generator: This is a class in TensorFlow that represents a random number generator. It provides methods for generating random numbers according to various distributions.

* from_seed(1000): This method is used to create a random number generator with a specific seed value. Setting a seed ensures that the sequence of random numbers generated will be the same each time the code is run, which can be useful for reproducibility purposes. In this case, the seed value is 1000.

In [ ]:
rand_mat = tf.random.Generator.from_seed(10)
rand_mat

In [ ]:
# Noe normalize the rand_mat to see the result
rand_mat.normal(shape=(2,5))


<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[ 2.2598648 , -0.40633026, -0.49845287,  0.8131295 ,  0.91097647],
       [-0.71561515,  1.2538986 , -0.9133161 ,  0.14227456, -1.1358311 ]],
      dtype=float32)>

In [ ]:
# Generate only random positive values between 0 and 1
positive_val = rand_mat.uniform(shape=(3,3))
positive_val

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.93598676, 0.6513264 , 0.31663585],
       [0.00111556, 0.9212191 , 0.3822806 ],
       [0.77246034, 0.91514194, 0.5751133 ]], dtype=float32)>

In [ ]:
# Generate random negative values between -1 and 0
negative_val = -rand_mat.uniform(shape=(3,3))
negative_val

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.8412577 , -0.22276926, -0.43761337],
       [-0.91387856, -0.6952636 , -0.694329  ],
       [-0.59417605, -0.5216116 , -0.8908236 ]], dtype=float32)>

In [ ]:
# Generate full integer with positive values between 0 and 1
pos_with_int_val = rand_mat.uniform_full_int(shape=(3,3))
pos_with_int_val

<tf.Tensor: shape=(3, 3), dtype=uint64, numpy=
array([[ 7333587122777176277,  5573229653085819419,  2318300313781036525],
       [15605695425603552690, 10631122849226110494, 16110049122128045967],
       [16177104077001528204,  7193369991975249249,  1665486291614692728]],
      dtype=uint64)>

In [ ]:
# Generate random integers with negative values in the range [-100, 0)
neg_with_int_val = -g.uniform(shape=(3, 3), maxval=100, dtype=tf.int32)

# Display the generated values
print("Random Integers with Negative Values:")
print(neg_with_int_val)


Random Integers with Negative Values:
tf.Tensor(
[[-91 -71  -9]
 [-53 -27 -28]
 [-40 -32 -54]], shape=(3, 3), dtype=int32)


In [ ]:
# create random tensor using `from_non_deterministic_state()`
gen = tf.random.Generator.from_non_deterministic_state()
gen

In [ ]:
# now normalize the gen tensor to show whats going on it
gen.normal(shape=(3,3))


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.80658764, -1.4260671 ,  0.62436914],
       [-0.37964737, -0.24740124, -0.75234574],
       [-0.01929025, -1.0216737 ,  0.09000548]], dtype=float32)>


All the constructors allow explicitly choosing an Random-Number-Generation (RNG) algorithm. Supported algorithms are "*philox*" and "*threefry*". For example:

In [ ]:
gen = tf.random.Generator.from_seed(123, alg='philox')
gen.normal(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.8673864 , -0.29899067, -0.9310337 ],
       [-1.5828488 ,  1.2481191 , -0.6770643 ]], dtype=float32)>

In [ ]:
# prompt: generate tf.random.Generate using threefry algorithm

gen = tf.random.Generator.from_seed(100, alg="threefry")
gen

In [ ]:
# prompt: now show gen using shape of 2,3

gen.normal(shape=(2,3))


UnimplementedError: {{function_node __wrapped__RngReadAndSkip_device_/job:localhost/replica:0/task:0/device:CPU:0}} Non-XLA devices don't support the ThreeFry algorithm. [Op:RngReadAndSkip] name: 

In [ ]:
print(gen.algorithm)

2


In [ ]:
g = tf.random.Generator.from_seed(123, alg="philox")
g.normal(shape=(20, 3))

<tf.Tensor: shape=(20, 3), dtype=float32, numpy=
array([[ 0.8673864 , -0.29899067, -0.9310337 ],
       [-1.5828488 ,  1.2481191 , -0.6770643 ],
       [ 0.0191265 , -0.29333332, -0.35438988],
       [ 0.07048975, -0.4882456 , -0.56108433],
       [-0.9890895 , -0.474985  , -1.3177569 ],
       [-1.7482879 , -1.6292503 ,  0.48826352],
       [-1.8867823 ,  0.18151656,  0.24483992],
       [ 0.37554732,  1.6184237 ,  0.34223038],
       [-0.3702979 , -0.99169385,  0.07253284],
       [ 0.2959086 , -0.31781763,  0.8365819 ],
       [ 1.44539   ,  0.5045312 , -0.7224314 ],
       [-0.09014846,  0.12777153, -0.06497782],
       [ 1.3639344 ,  1.5162361 , -0.5160658 ],
       [-1.5031487 ,  0.78185356,  0.669054  ],
       [ 0.5000064 ,  0.7658164 , -0.19813427],
       [ 1.1101567 ,  0.8233347 ,  2.454505  ],
       [-0.21202633,  0.6495798 , -0.29113603],
       [ 0.40688646, -0.25519267,  0.17281583],
       [ 2.6145976 ,  1.8622545 ,  0.73743194],
       [-0.0129986 ,  0.7771184 , -0.00

In [ ]:
# check status of a random number generator using state
g.state

<tf.Variable 'StateVar:0' shape=(3,) dtype=int64, numpy=array([15483,     0,     0])>

There is also a global generator:

In [ ]:
g = tf.random.get_global_generator()
g

In [ ]:
g.normal(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.02681838,  0.88260144, -0.587048  ],
       [ 1.3738587 , -0.9098388 , -1.9626236 ]], dtype=float32)>

**tf.distribute.Strategy**

In [ ]:
strt = tf.distribute.MirroredStrategy(devices=["cpu:0","cpu:1"])
with strt.scope():
  g = tf.random.Generator.from_seed(1)
  def f():
    return g.normal([])
  res = strt.run(f).values

In [ ]:
strat = tf.distribute.MirroredStrategy(devices=["cpu:0", "cpu:1"])
with strat.scope():
  g = tf.random.Generator.from_seed(1)
  def f():
    return g.normal([])
  results = strat.run(f).values

In [ ]:
# samples has shape [1, 5], where each value is either 0 or 1 with equal
# probability.
samples = tf.random.categorical(tf.math.log([[0.5, 0.5]]), 5)
samples

<tf.Tensor: shape=(1, 5), dtype=int64, numpy=array([[1, 0, 1, 0, 1]])>

**What happen when we change the seed?**

In [ ]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3,2))
random2 = tf.random.Generator.from_seed(11)
random2 = random2.normal(shape=(3,2))

# Check the tensors and see if they are equal
random1,random2==random2,random1 == random1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)


What if you wanted to shuffle the order of a tensor?

Wait, why would you want to do that?

Let's say you working with 15,000 images of cats and dogs and the first 10,000 images of were of cats and the next 5,000 were of dogs. This order could effect how a neural network learns (it may overfit by learning the order of the data), instead, it might be a good idea to move your data around.

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# lets shuffle the not_shuffled variable & get different resulg
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Shuffle in the same order every time using the seed parameter (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:

# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

# Other ways to make tensors

In [ ]:
# make a tensor of all ones
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
# make a tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

The main difference between tensors and NumPy arrays is that tensors can be run on GPUs.

    🔑 Note: A matrix or tensor is typically represented by a capital letter(e.g. X or A) where as a vector is typically represented by a lowercase

In [ ]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
A = tf.constant(numpy_A, shape = (2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# Getting information from tensors (shape, rank, size)

* Shape: The length (number of elements) of each of the dimensions of a tensor.
* Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
* Axis or Dimension: A particular dimension of a tensor.
* Size: The total number of items in the tensor.



In [2]:
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [10]:
# Get various attributes of tensor

print(f"Datatype of every element {rank_4_tensor.dtype}")
print(f"rank_4_tensor shape {rank_4_tensor.shape}")
print(f"rank_4_tensor ndim {rank_4_tensor.ndim}")
print(f"rank_4_tensor size {tf.size(rank_4_tensor)}")
print(f"Elements along axis 0 of tensor {rank_4_tensor.shape[0]}")
print(f"Elements along last axis of tensor {rank_4_tensor.shape[-1]}")


Datatype of every element <dtype: 'float32'>
rank_4_tensor shape (2, 3, 4, 5)
rank_4_tensor ndim 4
rank_4_tensor size 120
Elements along axis 0 of tensor 2
Elements along last axis of tensor 5


In [11]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [12]:

# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [13]:

# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

In [14]:

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [15]:

# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [16]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

# Manipulating tensors (tensor operations)
Finding patterns in tensors (numberical representation of data) requires manipulating them.
## Basic operations
You can perform many of the basic mathematical operations directly on tensors using Pyhton operators such as, `+`,` -`,` *`

In [19]:
tens = tf.constant([[10,7],[3,4]])
tens

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [22]:
# add some numbers
tens + 2

used `tf.constant()`, the original tensor is unchanged (the addition gets done on a copy).

In [21]:
tens

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [24]:
copy_tens = tens + 10
copy_tens

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [26]:
# deduction
copy_tens - 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-80, -83],
       [-87, -86]], dtype=int32)>

In [25]:
# Multiplication
tens * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [29]:
# use tensorflow function equivalent of the 1 `*` (multiply)
tf.multiply(tens,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [30]:
tf.add(tens, tens)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]], dtype=int32)>

In [32]:
tf.subtract(copy_tens,tens)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10, 10]], dtype=int32)>

# Matrix multiplication
One of the most common operations in machine learning algorithms is matrix multiplication.

TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.


In [39]:
# create a tensor
A = tf.constant([[2,4],[1,8]])
B = tf.constant([[9,7],[8,6]])
A, B

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 4],
        [1, 8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[9, 7],
        [8, 6]], dtype=int32)>)

In [40]:
A @ B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 38],
       [73, 55]], dtype=int32)>

In [41]:
# create a tensor
X = tf.constant([[2,3,4],[1,6,8]])
Y = tf.constant([[9,7],[8,6]])
X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [2,3], In[1]: [2,2] [Op:MatMul] name: 

To multiply different dimension matrix we need to either:
* Reshape  `tf.reshape()`
* Transpose `tf.transpose()`

In [48]:
# Let's try a reshape first
reshape_X = tf.reshape(X, shape = (2,3))
reshape_X

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [1, 6, 8]], dtype=int32)>

In [55]:
transpose_X = tf.transpose(reshape_X)
transpose_X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [3, 6],
       [4, 8]], dtype=int32)>

In [56]:
# Now we can multiply transpose_X and Y. because these two matrix are
# same shape
transpose_X @ Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 26,  20],
       [ 75,  57],
       [100,  76]], dtype=int32)>

In [57]:
Y.shape

TensorShape([2, 2])

Above work such reshape then transpose then multiply can work in one
function called `tf.matmul`. Here is how we do this

In [58]:
X.shape, Y.shape

(TensorShape([2, 3]), TensorShape([2, 2]))

In [59]:
X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [2,3], In[1]: [2,2] [Op:MatMul] name: 

In [60]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 26,  20],
       [ 75,  57],
       [100,  76]], dtype=int32)>

 calling `tf.reshape()` and `tf.transpose()`  don't necessarily result in the same values.

In [66]:
# Create another (3, 2) tensor
A = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
A

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [67]:
print("Normal A:")
print(A, "\n")
print("A reshaped to (2, 3):")
print(tf.reshape(A, (2, 3)), "\n")

print("A transposed:")
print(tf.transpose(A))

Normal A:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

A reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

A transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [69]:
# create a new tensor with default datatype (float32)
B = tf.constant([1.5,9.4])
# create a new tensor with default datatype (int32)
C = tf.constant([1,7])
B,C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 9.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [70]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.5, 9.4], dtype=float16)>

In [71]:
# change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

# Getting the absolute value
`tf.abs()`

In [73]:
D = tf.constant([-70,-3])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-70,  -3], dtype=int32)>

In [74]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([70,  3], dtype=int32)>

# Finding the min, max, mean, sum (aggregation)

* tf.reduce_min() - find the minimum value in a tensor.
* tf.reduce_max() - find the maximum value in a tensor (helpful for when you
  want to find the highest prediction probability).
* tf.reduce_mean() - find the mean of all elements in a tensor.
* tf.reduce_sum() - find the sum of all elements in a tensor.
* Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().

In [78]:
# create a tensor with 50 random values between 0 to 100
import numpy as np

E = tf.constant(np.random.randint(low=0,high=1000,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([256,  20, 563, 637, 143, 546, 980, 417, 449, 843, 499, 335, 743,
       502,  79, 125, 996, 783, 458, 960, 878, 653, 325, 346, 607, 926,
       632, 497, 985, 884, 836, 429, 779,  55, 773, 506, 299, 866, 749,
       992, 803, 824, 733, 156, 207, 461, 249,  51, 106, 868])>

In [81]:
# find the maximum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=20>

In [82]:
# find the minimum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=996>

In [83]:
# find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=556>

In [84]:
# find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=27809>

In [85]:
# Find the maximum element position of F
tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [87]:
# Find the minimum element position of F
tf.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [89]:
# Find the minimum element position of F
tf.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [90]:
# Find the maximum element position of F
print(f"The maximum value of E is at position: {tf.argmax(E).numpy()}")
print(f"The maximum value of E is: {tf.reduce_max(E).numpy()}")
print(f"Using tf.argmax() to index E, the maximum value of E is: {E[tf.argmax(E)].numpy()}")
print(f"Are the two max values the same (they should be)? {E[tf.argmax(E)].numpy() == tf.reduce_max(E).numpy()}")


The maximum value of E is at position: 16
The maximum value of E is: 996
Using tf.argmax() to index E, the maximum value of E is: 996
Are the two max values the same (they should be)? True


# Squeezing a tensor (removing all single dimensions)
use tf.squeeze().

tf.squeeze() - remove all dimensions of 1 from a tensor.

In [91]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [92]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

In [93]:
G_squeezed

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([97, 89,  3, 28, 27, 23, 82, 58, 67, 27, 41, 85, 94, 22, 72, 63,  9,
       93, 28, 18, 47,  3, 79, 82, 56, 41, 18, 99, 54, 69, 57, 58, 68, 10,
       29, 19, 35, 45, 47, 78, 40, 96, 97, 50, 53, 57, 16, 33, 20, 34])>

# `Using` `@tf.function`

In [96]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)


<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [98]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>