In this notebook to cover:

*   Introduction to tensors
*   Getting information from tensor
*   Manipulating tensors
*   Tensors & NumPy
*   Using @tf.function (a way to boost up speed to a regular python function)
*   Using GPUs with Tensorflow
*   Exercises to try for yourself!





# Introduction to Tensors

In [1]:
# Import Tensroflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [4]:
# tf.constent tensor
t_scale = tf.constant(7)
t_scale

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# check the number of dimension of a tensor (ndim)
t_scale.ndim

0

In [6]:
# create a vector
vector_t = tf.constant([8,64])
vector_t

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 8, 64], dtype=int32)>

In [9]:
#check the dimension of vector
vector_t.ndim

1

In [10]:
# creating a matrix (1D)
matrix = tf.constant([[10,7],
                      [7,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 11]], dtype=int32)>

In [11]:
matrix.ndim

2

In [12]:
a_matrix = tf.constant([[11.5,9.3],
                        [13.8,5.2],
                         [9.3,6.5]])
a_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11.5,  9.3],
       [13.8,  5.2],
       [ 9.3,  6.5]], dtype=float32)>

In [13]:
# lets check the dimensions of a_matrix
a_matrix.ndim

2

In [14]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [15]:
tensor.ndim

3


What created so far:

*   Scalar: a single number
*   Vector: a number with direction (e.g. wind speed and direction)
*   Matrix: a 2-dimensional array of numbers
*   Tensor: an n-dimensional array of numbers (when n can be any number, a *  
*   0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

# Creating tensors with tf.Variable


In [17]:
# create the same tensor with tf.Variable()
changeable_tensor = tf.Variable([10,7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [19]:
changeable_tensor[0] = 70
changeable_tensor[1] = 100
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [20]:
# How about we try .assign()
changeable_tensor[0].assign(70)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([70,  7], dtype=int32)>

In [21]:
another_chnge_tensor = tf.Variable([[[10,5,6],[12,15,18,],[17,20,23]]])
another_chnge_tensor

<tf.Variable 'Variable:0' shape=(1, 3, 3) dtype=int32, numpy=
array([[[10,  5,  6],
        [12, 15, 18],
        [17, 20, 23]]], dtype=int32)>

In [33]:
# prompt: another_chnge_tensor[1].assign([1,2,3])
# InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:CPU:0}} slice index 1 of dimension 0 out of bounds. [Op:StridedSlice] name: strided_slice/

another_chnge_tensor[0,0].assign([20,25,36])
another_chnge_tensor[0,1].assign([24,30,36])
another_chnge_tensor[0,2].assign([1,2,3])



<tf.Variable 'UnreadVariable' shape=(1, 3, 3) dtype=int32, numpy=
array([[[20, 25, 36],
        [24, 30, 36],
        [ 1,  2,  3]]], dtype=int32)>

In [34]:
another_chnge_tensor

<tf.Variable 'Variable:0' shape=(1, 3, 3) dtype=int32, numpy=
array([[[20, 25, 36],
        [24, 30, 36],
        [ 1,  2,  3]]], dtype=int32)>

In [37]:
# if i want to change it at a time . it can do this way
another_chnge_tensor[0].assign([[1,2,3],[4,5,6],[7,8,9]])
another_chnge_tensor

<tf.Variable 'Variable:0' shape=(1, 3, 3) dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [40]:
# Let's try change our unchangable tensor
unchangeable_tensor = tf.constant([10, 7])
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [41]:
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

🔑 Note: Rarely in practice will you need to decide whether to use tf.constant or tf.Variable to create tensors, as TensorFlow does this for you. However, if in doubt, use tf.constant and change it later if needed.

# Creating random tensors
Random tensors are tensors of some arbitrary size which contain random numbers

In [46]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [50]:
g = tf.random.Generator.from_seed(1000)
g

In [53]:
g.normal(shape=(1, 2, 3))

<tf.Tensor: shape=(1, 2, 4, 3), dtype=float32, numpy=
array([[[[ 1.0030682 , -0.8947577 ,  0.7238131 ],
         [ 0.27466977,  1.3872291 ,  1.3994837 ],
         [ 0.1577325 , -0.5907422 , -0.60189474],
         [-0.40215513,  0.04168779, -0.8780139 ]],

        [[ 1.1845666 , -0.79202986, -1.5191468 ],
         [ 1.5311124 ,  1.4577291 ,  0.5478101 ],
         [ 0.9334445 , -1.5754578 ,  0.70275563],
         [ 1.5519783 , -1.9333141 ,  0.5660382 ]]]], dtype=float32)>

In [55]:
g.normal(shape=(2,5,5))

<tf.Tensor: shape=(2, 5, 5), dtype=float32, numpy=
array([[[-2.1877253 , -0.16194105, -0.34815148, -0.23865847,
          0.05823248],
        [ 0.47166824,  1.2638935 , -0.8244765 , -0.71548617,
         -1.7906119 ],
        [-0.8731837 , -0.37652206,  1.2323543 , -0.5825653 ,
         -1.9579847 ],
        [-0.21332331, -0.34466   ,  0.8164751 , -0.39260462,
          1.0732925 ],
        [ 0.14255638, -0.84050477,  0.02893499, -0.9648049 ,
          0.07207965]],

       [[-1.9269958 , -0.2908789 , -0.4989587 , -0.00353788,
         -0.9623533 ],
        [-1.8963418 , -0.66458935, -1.3025154 , -1.4493096 ,
         -1.1303661 ],
        [ 1.1918781 , -1.1623456 , -0.2333405 , -0.47908613,
         -0.3198692 ],
        [ 0.88944876, -0.6474925 , -1.2720575 ,  0.01439076,
          0.5337753 ],
        [ 0.6845374 , -0.47580412,  2.0813363 ,  0.3328288 ,
         -0.07335203]]], dtype=float32)>

On the above cover:

* tf.random.Generator: This is a class in TensorFlow that represents a random number generator. It provides methods for generating random numbers according to various distributions.

* from_seed(1000): This method is used to create a random number generator with a specific seed value. Setting a seed ensures that the sequence of random numbers generated will be the same each time the code is run, which can be useful for reproducibility purposes. In this case, the seed value is 1000.

In [58]:
rand_mat = tf.random.Generator.from_seed(10)
rand_mat

In [66]:
# Noe normalize the rand_mat to see the result
rand_mat.normal(shape=(2,5))


<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[ 2.2598648 , -0.40633026, -0.49845287,  0.8131295 ,  0.91097647],
       [-0.71561515,  1.2538986 , -0.9133161 ,  0.14227456, -1.1358311 ]],
      dtype=float32)>

In [63]:
# Generate only random positive values between 0 and 1
positive_val = rand_mat.uniform(shape=(3,3))
positive_val

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.21067083, 0.51177466, 0.41932762],
       [0.15842211, 0.92089975, 0.02824986],
       [0.19037974, 0.6370027 , 0.94134784]], dtype=float32)>

In [65]:
# Generate random negative values between -1 and 0
negative_val = -rand_mat.uniform(shape=(3,3))
negative_val

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.8485732 , -0.27886426, -0.7631234 ],
       [-0.18322289, -0.96699893, -0.6871413 ],
       [-0.28245473, -0.03297281, -0.01463544]], dtype=float32)>

In [67]:
# Generate full integer with positive values between 0 and 1
pos_with_int_val = rand_mat.uniform_full_int(shape=(3,3))
pos_with_int_val

<tf.Tensor: shape=(3, 3), dtype=uint64, numpy=
array([[ 5165482742405318071,  9220733246027269034, 10510068773316523641],
       [17396237953115605330,  1856748070021535862, 10178666331051626957],
       [ 4238482924337022990, 11715610112966722032, 15101557774008816907]],
      dtype=uint64)>

In [75]:
# Generate random integers with negative values in the range [-100, 0)
neg_with_int_val = -g.uniform(shape=(3, 3), maxval=100, dtype=tf.int32)

# Display the generated values
print("Random Integers with Negative Values:")
print(neg_with_int_val)


Random Integers with Negative Values:
tf.Tensor(
[[-20 -49   0]
 [-59 -47 -14]
 [-33 -23 -60]], shape=(3, 3), dtype=int32)
