#TensorFlow 2.0 Introduction
In this notebook you will be given an interactive introduction to TensorFlow 2.0. We will walk through the following topics within the TensorFlow module:

- TensorFlow Install and Setup
- Representing Tensors
- Tensor Shape and Rank
- Types of Tensors


If you'd like to follow along without installing TensorFlow on your machine you can use **Google Collaboratory**. Collaboratory is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud.

## Importing TensorFlow
The first step here is going to be to select the correct version of TensorFlow from within collabratory!


In [1]:
import tensorflow as tf
print(tf.__version__)

2.15.0


##Tensors
"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

It should't surprise you that tensors are a fundemental apsect of TensorFlow. They are the main objects that are passed around and manipluated throughout the program. Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape.

**Data Types Include**: float32, int32, string and others.

**Shape**: Represents the dimension of data.

Just like vectors and matrices tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.

In the next sections we will discuss some different properties of tensors. This is to make you more familiar with how tensorflow represnts data and how you can manipulate this data.


###Creating Tensors
Below is an example of how to create some different tensors.

You simply define the value of the tensor and the datatype and you are good to go! It's worth mentioning that usually we deal with tensors of numeric data, it is quite rare to see string tensors.

For a full list of datatypes please refer to the following guide.

https://www.tensorflow.org/api_docs/python/tf/dtypes/DType?version=stable

In [2]:
number = tf.Variable(324)
print(number)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>


In [3]:
string = tf.Variable('This is simple sentence')
print(string)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is simple sentence'>


In [4]:
floating = tf.Variable(5.59)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.59>


We can fixed the datatype of any tensor. examples are given below

In [6]:
name = tf.Variable('My name is sujon', tf.string)

number = tf.Variable(25422,tf.int8)
grade = tf.Variable(4.56, tf.float16)
print(name)
print(number)
print(grade)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'My name is sujon'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=25422>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=4.56>


###Rank/Degree of Tensors
Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a *tensor of rank 0*, also known as a scalar.

Now we'll create some tensors of higher degrees/ranks.

In [7]:
rank1_tensor = tf.Variable(['Test'], tf.string)
rank2_tensor = tf.Variable([['test', 'ok'],['test','yes']], tf.string)

In [8]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [10]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

Another example of `tf.rank`. This helps to Returns a 0-D int32 Tensor representing the rank of input.

  Note: The rank of a tensor is not the same as the rank of a matrix. The rank of a tensor is the number of indices required to uniquely select each element of the tensor. Rank is also known as "order", "degree", or "ndims."

In [14]:
T = tf.Variable([[[2,45,5,5],[10,-1,3,4],[5,7,9,13]]])
T

<tf.Variable 'Variable:0' shape=(1, 3, 4) dtype=int32, numpy=
array([[[ 2, 45,  5,  5],
        [10, -1,  3,  4],
        [ 5,  7,  9, 13]]], dtype=int32)>

In [15]:
tf.rank(T)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [16]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

###Shape of Tensors
Now that we've talked about the rank of tensors it's time to talk about the shape. The shape of a tensor is simply the number of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes it may be unknown.

To **get the shape** of a tensor we use the shape attribute.


In [17]:
rank1_tensor.shape

TensorShape([1])

In [18]:
rank2_tensor.shape

TensorShape([2, 2])

In [19]:
name.shape

TensorShape([])

In [20]:
grade.shape

TensorShape([])

###Changing Shape
The number if elements of a tensor is the product of the sizes of all its
shapes. There are often many shapes that have the same number of elements,
making it convient to be able to change the shape of tensor.

The example below shows to change the shape of tensor.

In [26]:
tensor1 = tf.ones([1,2,3])
# lets change the shape of tensor1 and put it to reshape_tensor1
reshape_tensor1 = tf.reshape(tensor1, [2,1,3])

In [27]:
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [28]:
reshape_tensor1

<tf.Tensor: shape=(2, 1, 3), dtype=float32, numpy=
array([[[1., 1., 1.]],

       [[1., 1., 1.]]], dtype=float32)>

Note : changing tensor shape . so, must match multiplication values such as 1* 2 * 3 == 2 * 1 * 3. Either it cant change the shape of any tensor.

In [35]:
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,25],
          [15,16,17,18,30]]


tensor = tf.Variable(matrix, dtype = tf.int32)
print(tensor)
print(tensor.shape)
print(tf.rank(tensor))

<tf.Variable 'Variable:0' shape=(4, 5) dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 25],
       [15, 16, 17, 18, 30]], dtype=int32)>
(4, 5)
tf.Tensor(2, shape=(), dtype=int32)


Lets chage tensor shape

In [39]:
reshape_tensor2 = tf.reshape(tensor, [2,2,5])
reshape_tensor2

<tf.Tensor: shape=(2, 2, 5), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 25],
        [15, 16, 17, 18, 30]]], dtype=int32)>

In [42]:
reshape_tensor3 = tf.reshape(tensor, [2,5,2])
reshape_tensor3

<tf.Tensor: shape=(2, 5, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [25, 15],
        [16, 17],
        [18, 30]]], dtype=int32)>

###Slicing Tensors
You may be familiar with the term "slice" in python and its use on lists, tuples etc. Well the slice operator can be used on tensors to select specific axes or elements.

When we slice or select elements from a tensor, we can use comma seperated values inside the set of square brackets. Each subsequent value refrences a different dimension of the tensor.

Ex: ```tensor[dim1, dim2, dim3]```

I've included a few examples that will hopefully help illustrate how we can manipulate tensors with the slice operator.

In [43]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32)
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [49]:
# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)


###Types of Tensors
Before we go to far, I will mention that there are diffent types of tensors. These are the most used and we will talk more in depth about each as they are used.
- Variable
- Constant
- Placeholder
- SparseTensor

With the execption of ```Variable``` all these tensors are immuttable, meaning their value may not change during execution.

For now, it is enough to understand that we use the Variable tensor when we want to potentially change the value of our tensor.

