#  Trained a machine learning model using a prebuilt dataset using the Keras API.

## Tensorflow quickstart for beginners
This short introduction users `keras` library to :
1. Load a prebuild dataset.
2. Build a neural network machine learning model that classifies images.
3. Train this neural network.
4. Evaluate the accuracy of the model.

In [1]:
import tensorflow as tf

### Load a dataset

In [3]:
mnist = tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_test)=mnist.load_data()
# pixal value to divided 255
x_train ,x_test = x_train/255.0, x_test/255.0



In [4]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

### Build a machine larning model

In [5]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)

])


In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101770 (397.54 KB)
Trainable params: 101770 (397.54 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [7]:
prediction = model([x_train[:1]])

In [8]:
prediction

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[-0.39941642, -0.94110984, -0.8312586 ,  0.7174865 ,  0.8552271 ,
         0.04414712,  0.06255192,  0.5604939 , -0.2572955 ,  0.32634148]],
      dtype=float32)>

In [9]:
tf.nn.softmax(prediction)

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.05627791, 0.03274037, 0.03654192, 0.17195024, 0.19734347,
        0.08769508, 0.08932403, 0.14696765, 0.06487246, 0.11628687]],
      dtype=float32)>

In [10]:
## define a loss function
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [13]:
loss_fn(y_train[:1], prediction).numpy()

2.4338896

In [14]:
## compile the model
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [15]:
model

### Train and evaluate your model

In [16]:
model.fit(x_train,y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2928 - accuracy: 0.9154
Epoch 2/5
1875/1875 [==============================] - 13s 7ms/step - loss: 0.1433 - accuracy: 0.9575
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1077 - accuracy: 0.9669
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0872 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0755 - accuracy: 0.9760


In [17]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0786 - accuracy: 0.9757


[0.07863009721040726, 0.9757000207901001]

In [19]:
import numpy as np
import sklearn.metrics as metrics

y_pred = model.predict(x_test)
y_pred = np.argmax(y_pred, axis=1)
print(metrics.classification_report(y_test, y_pred))


313/313 [==============================] - 1s 3ms/step
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.97      0.97      1032
           3       0.97      0.98      0.97      1010
           4       0.98      0.98      0.98       982
           5       0.98      0.97      0.98       892
           6       0.98      0.97      0.98       958
           7       0.97      0.97      0.97      1028
           8       0.97      0.96      0.97       974
           9       0.97      0.97      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000



In [28]:
# prompt: test the model from  user input 0 to 9

user_input = int(input("Enter a number between 0 and 9: "))
try:
  while(user_input == True):
    if user_input < 0 or user_input > 9:
        print("Invalid input. Please enter a number between 0 and 9.")
    else:
        test_image = x_test[user_input]
        test_image = np.expand_dims(test_image, axis=0)
        prediction = model.predict(test_image)
        predicted_class = np.argmax(prediction)
        print(f"The predicted class is: {predicted_class}")
except ValueError:
  print("Input only numbers 0 to 9")


Enter a number between 0 and 9: 5


In [32]:
def test_model():
  """Prompts user for input, tests the model, and displays prediction."""
  while True:
    try:
      user_input = int(input("Enter a number between 0 and 9 (or enter 'q' to quit): "))
      if user_input == 'q':
        break
      if user_input < 0 or user_input > 9:
        print("Invalid input. Please enter a number between 0 and 9.")
      else:
        # Assuming x_test and model are defined elsewhere
        test_image = x_test[user_input]
        test_image = np.expand_dims(test_image, axis=0)
        prediction = model.predict(test_image)
        predicted_class = np.argmax(prediction)
        print(f"The predicted class is: {predicted_class}")
    except ValueError:
      print("Invalid input. Please enter a number between 0 and 9 (or 'q' to quit).")

# Call the function to initiate the testing loop
test_model()


Enter a number between 0 and 9 (or enter 'q' to quit): 5
1/1 [==============================] - 0s 31ms/step
The predicted class is: 1
Enter a number between 0 and 9 (or enter 'q' to quit): 5
1/1 [==============================] - 0s 21ms/step
The predicted class is: 1
Enter a number between 0 and 9 (or enter 'q' to quit): q
Invalid input. Please enter a number between 0 and 9 (or 'q' to quit).
Enter a number between 0 and 9 (or enter 'q' to quit): q
Invalid input. Please enter a number between 0 and 9 (or 'q' to quit).
Enter a number between 0 and 9 (or enter 'q' to quit): q
Invalid input. Please enter a number between 0 and 9 (or 'q' to quit).
Enter a number between 0 and 9 (or enter 'q' to quit): q
Invalid input. Please enter a number between 0 and 9 (or 'q' to quit).
Enter a number between 0 and 9 (or enter 'q' to quit): 6
1/1 [==============================] - 0s 22ms/step
The predicted class is: 4


KeyboardInterrupt: Interrupted by user

In [31]:

from sklearn.metrics import confusion_matrix

# Get the predicted labels for the test data
y_pred = model.predict(x_test)
y_pred = np.argmax(y_pred, axis=1)

# Generate the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print(cm)


313/313 [==============================] - 1s 2ms/step
[[ 974    1    1    0    0    2    0    1    1    0]
 [   0 1121    4    0    0    1    3    1    5    0]
 [   5    2 1001    7    0    0    2    5   10    0]
 [   1    0    3  988    0    4    0    6    3    5]
 [   2    0    1    0  958    1    6    2    1   11]
 [   2    0    0   10    2  869    3    1    3    2]
 [   8    2    2    1    4    7  932    0    2    0]
 [   2    7   11    1    1    0    0  997    1    8]
 [   8    0    3    6    4    4    2    5  938    4]
 [   2    2    0    6    9    2    1    8    0  979]]
